#
# Makefile
#
# $Id: //poco/1.4/CppUnit/Makefile#1 $
#
# Makefile for Poco CppUnit
#
#POCO_BUILD = ..

include $(POCO_BASE)/build/rules/global

objects = LibraryDateParser

target         = LibLibrary
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
