#
# Makefile
#
# $Id: //poco/1.4/CppUnit/Makefile#1 $
#
# Makefile for Poco CppUnit
#

include $(POCO_BASE)/build/rules/global

objects = Driver DueDateParserTest DummyTest LibraryTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoFoundation CppUnit LibLibrary

include $(POCO_BASE)/build/rules/exec
